theme: jekyll-theme-minimal
title: School of Representational Art
description: A classical art education in a modern world
logo: [/images/logo.jpg]
show_downloads: ["true" or "false" to indicate whether to provide a download URL]
google_analytics: [Your Google Analytics tracking ID]
